cart/urls.py
"""Urls list for 'userprofile' app."""

from django.urls import path

from .views import CartView

app_name = "cart"

urlpatterns = [
    path("<slug:region_slug>/cart/", CartView.as_view(), name="cart"),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("location.urls")),
    path("", include("orders.urls")),
    path("", include("feedback.urls")),
    path("", include("cart.urls")),
    path("", include("mainpage.urls")),
    path("", include("fillers.urls")),
    path("catalogue/", include("catalogue.urls")),
    path("delivery_and_payment/", include("delivery_and_payment.urls")),
    path("reviews/", include("reviews.urls")),
    path("product/", include("products.urls")),
    path("zoho-token/", include("zoho_token.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainpage/urls.py
"""Urls list for 'mainpage' app."""
from django.urls import path

from .views import MainPageView

app_name = "main_page"

urlpatterns = [
    path("", MainPageView.as_view(), name="main_page"),
    path("<slug:region_slug>/", MainPageView.as_view(), name="mainpage-view"),
]

orders/urls.py
"""Orders urls."""
from django.urls import path

from .views import CheckoutView, IndividualOrders, OrdersList, QuickOrders

app_name = "orders"

urlpatterns = [
    path(
        "individual-orders/",
        IndividualOrders.as_view(),
        name="individual-order",
    ),
    path(
        "quick-orders/",
        QuickOrders.as_view(),
        name="quick-order",
    ),
    path("<slug:region_slug>/checkout/", CheckoutView.as_view(), name="checkout"),
    path("<slug:region_slug>/orders/", OrdersList.as_view(), name="orders-list"),
]

products/urls.py
"""Urls for 'products' app."""

from django.urls import path

from .views import ProductSearchView, ProductView

app_name = "products"

urlpatterns = [
    path(
        "<slug:region_slug>/",
        ProductSearchView.as_view(),
    ),
    path(
        "<slug:region_slug>/<slug:subcategory_slug>/<slug:product_slug>/",
        ProductView.as_view(),
        name="product",
    ),
]

cart/models.py
"""Models of the cart."""
from django.db import models

# Create your models here.

cart/views.py
"""Views of the cart."""

import json
from typing import Any

from django.http import HttpRequest, HttpResponse, HttpResponseServerError, JsonResponse

from async_views.generic.base import AsyncTemplateView
from services.common_handlers import common_handlers
from services.data_getters import crm_data
from services.mixins import ApplicationMixin

from .app_services.session_data import session_data
from .app_services.utils import formatters


class CartView(AsyncTemplateView, ApplicationMixin):
    """Class view for process adding product to customer ordered products."""

    http_method_names = ["post", "put", "delete", "get"]
    template_name = "cart/index.html"

    async def get(self, request, *args, **kwargs) -> HttpResponse:
        """Asynchronous variation of GET method."""
        context = await self.get_context_data(**kwargs)
        if isinstance(context, HttpResponseServerError):
            return context
        response = self.render_to_response(context)
        response["Cache-Control"] = "no-store"
        return response

    async def get_context_data(self, **kwargs: Any) -> dict[str, list[dict[str, Any]]]:
        """
        Get context data.

        :param kwargs: any keyword arguments.
        :return: A dictionary containing context data.
        """
        context: dict[str, list[dict[str, Any]]] = await self.get_common_context(
            **await super().get_context_data(**kwargs)
        )
        if isinstance(context, HttpResponseServerError):
            return context
        context["title"] = "Корзина"
        old_cart = await session_data.get_or_create_cart(self.request.session)
        region = context["region"]
        region_products = await self._get_region_products(
            region, context["selected_currency"], old_cart["products"]
        )
        context["cart"] = updated_cart = await self._update_cart_data(region_products, old_cart)

        context["cart_products"] = await formatters.format_cart_products(
            updated_cart,
            region_products,
            context["selected_currency"],
        )
        context["cart_grand_total_price"] = self._calculate_cart_grand_total_price(
            context["cart_products"]
        )
        context["suggested_products"] = await self._get_suggested_products(
            region, region_products, context["cart_products"]
        )
        context["is_cart"] = True
        return context

    async def _update_cart_data(
        self, region_products: list[dict[str, Any]], old_cart: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Update cart data in the context.

        :param context: The context dictionary.
        """
        outdated_cart_products_ids = await self._find_outdated_cart_products_ids(
            region_products, old_cart
        )
        await self._remove_outdated_cart_products(outdated_cart_products_ids)
        return await session_data.get_or_create_cart(self.request.session)

    async def _get_region_products(
        self,
        region: dict[str, Any],
        selected_currency: dict[str, str | float],
        cart_products: list[dict[str, int]],
    ) -> list[dict[str, Any]]:
        """
        Get region products based on the provided region and context.

        :param region: The region dictionary.
        :param context: The context dictionary.
        :return: A list of region products.
        """
        return await crm_data.get_region_products(
            region["slug"],
            currency=selected_currency,
            cart_ids_set={product["id"] for product in cart_products},
        )

    async def _find_outdated_cart_products_ids(
        self, region_products: list[dict[str, Any]], cart: dict[str, Any]
    ) -> tuple[dict[str, Any]]:
        """
        Find outdated cart products by comparing region products with the cart.

        :param region_products: list of region products.
        :param cart: The cart dictionary.
        :return: A list of outdated cart product IDs.
        """
        return {
            product["id"]
            for product in cart["products"]
            if product["id"] not in (product["id"] for product in region_products)
        }

    async def _remove_outdated_cart_products(
        self, outdated_cart_products_ids: tuple[str]
    ) -> None:
        """
        Remove outdated cart products from the session.

        :param outdated_cart_products: list of outdated cart product IDs.
        """
        await session_data.remove_ordered_products(
            self.request.session, outdated_cart_products_ids
        )

    async def _get_suggested_products(
        self, region: dict[str, Any], region_products: list[dict[str, Any]], cart_products
    ) -> list[dict[str, Any]]:
        """
        Get suggested products for the given region.

        :param region: The region dictionary.
        :param region_products: list of region products.
        :return: A list of suggested products.
        """
        return await common_handlers.get_first_three_additional_products(
            region["slug"], region_products, cart_products
        )

    def _calculate_cart_grand_total_price(
        self, cart_products: list[dict[str, Any]]
    ) -> float:  # TODO: to combine this method with CheckoutView.calculate_cart_grand_total
        """
        Calculate the grand total price of cart products.

        :param cart_products: list of cart products.
        :return: The grand total price.
        """
        return round(
            sum(
                map(
                    lambda x: (x["unit_price"] if not x["discount"] else x["new_price"])
                    * x["cart_amount"],
                    cart_products,
                )
            ),
            2,
        )

    async def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> JsonResponse:
        """Handle POST request for adding product to customer ordered products."""
        try:
            data: dict = json.loads(request.body)
        except json.JSONDecodeError:
            return JsonResponse({"msg": "Wrong data passed"}, status=400)

        if not all([(product_id := data.get("id")), (amount := data.get("amount"))]):
            return JsonResponse({"msg": "Product ID or amount isn't passed"}, status=400)

        if not isinstance(product_id, str):
            return JsonResponse(
                {"msg": "Product ID must be integer reduced to string"}, status=400
            )

        if not product_id.isdigit():
            return JsonResponse(
                {"msg": "Product ID isn't integer reduced to string"}, status=400
            )

        if not isinstance(amount, int):
            return JsonResponse({"msg": "Product amount must be integer"}, status=400)

        bouquet_size = data.get("bouquet_size")
        if bouquet_size:
            if not isinstance(bouquet_size, int):
                return JsonResponse({"msg": "Bouquet size must be integer"}, status=400)
        context: dict[str, list[dict[str, Any]]] = await self.get_common_context(
            *args, **kwargs
        )
        return await session_data.create_ordered_product(
            request,
            request.session,
            product_id,
            amount,
            context["region"],
            bouquet_size,
        )

    async def put(self, request: HttpRequest, *args: Any, **kwargs: dict) -> JsonResponse:
        """Handle PUT request for updating product to customer ordered products."""
        try:
            data: dict = json.loads(request.body)
        except json.JSONDecodeError:
            return JsonResponse({"msg": "Wrong data passed"}, status=400)

        if not all([(product_id := data.get("id")), (amount := data.get("amount"))]):
            return JsonResponse({"msg": "Product ID or amount isn't passed"}, status=400)

        if not isinstance(product_id, str):
            return JsonResponse(
                {"msg": "Product ID must be integer reduced to string"}, status=400
            )

        if not product_id.isdigit():
            return JsonResponse(
                {"msg": "Product ID isn't integer reduced to string"}, status=400
            )

        if not isinstance(amount, int):
            return JsonResponse({"msg": "Product amount must be integer"}, status=400)

        bouquet_size = data.get("bouquet_size")
        if bouquet_size:
            if not isinstance(bouquet_size, int):
                return JsonResponse({"msg": "Bouquet size must be integer"}, status=400)
        context: dict[str, list[dict[str, Any]]] = await self.get_common_context(
            *args, **kwargs
        )
        return await session_data.update_ordered_product(
            request, request.session, product_id, amount, context["region"], bouquet_size
        )

    async def delete(self, request: HttpRequest, *args: Any, **kwargs: Any) -> JsonResponse:
        """Handle Delete request for deleting ordered_products record."""
        try:
            data: dict = json.loads(request.body)
        except json.JSONDecodeError:
            return JsonResponse({"msg": "Wrong data passed"}, status=400)

        if not (product_id := data.get("id")):
            return JsonResponse({"msg": "Product ID isn't passed"}, status=400)

        if not isinstance(product_id, str):
            return JsonResponse(
                {"msg": "Product ID must be integer reduced to string"}, status=400
            )

        if not product_id.isdigit():
            return JsonResponse(
                {"msg": "Product ID isn't integer reduced to string"}, status=400
            )

        bouquet_size = data.get("bouquet_size")
        if bouquet_size:
            if not isinstance(bouquet_size, int):
                return JsonResponse({"msg": "Bouquet size must be integer"}, status=400)
        return await session_data.remove_ordered_product(
            request.session, product_id, bouquet_size
        )

cart/templates/cart/index.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{ title }}</title>

  <!-- FAVICON -->

  <link rel="shortcut icon" href="{% static 'mainpage/favicon.svg' %}" type="image/x-icon" />

  <!-- FOR-PHONE-INPUT -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

  <!-- BOOTSTRAP -->

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

  <!-- SITE-STYLE -->

  <link rel="stylesheet" href="{% static 'styles/swiper832.min.css' %}">
  <link rel="stylesheet" href="{% static 'styles/common.css' %}" />
  <link rel="stylesheet" href="{% static 'cart/styles.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/header.css' %}">
  <link rel="stylesheet" href="{% static 'styles/footer.css' %}">
  <link rel="stylesheet" href="{% static 'styles/sideButtons.css' %} " />
  <link rel="stylesheet" href="{% static 'styles/quickOrderModal.css' %}">
  <link rel="stylesheet" href="{% static 'styles/callBackModal.css' %}">
  <link rel="stylesheet" href="{% static 'styles/cardXlForSlider.css' %}">
  <link rel="stylesheet" href="{% static 'styles/cardLforCart.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/counter.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/cartOrdersSwitch.css' %}">
</head>

<body>
  <!-- HEADER -->
  {% include 'core_components/header.html' %}

  <main>
    <section class="container cart-container m-b-60">
      <!-- TITLE -->
      {% include 'core_components/cartOrdersSwitch.html' %}

      <!-- CART CARDS -->
      <div class="cart-cards-container">
        {% for product in cart_products %}
          <div
            class="card-l product-card"
            data-product-id="{{ product.id }}"
            data-product-new-price="{{ product.new_price }}"
            data-product-unit-price="{{ product.unit_price }}"
            data-region="{{ region.slug }}"
            data-is-bouquet="{{ product.is_bouquet }}"
            data-selected-size="{{ product.selected_size }}"
            itemscope
            itemtype="http://schema.org/Product"
          >
            {% if product.discount %}
              <div class="discount">
                <p class="p-16-auto-medium white">
                  {{ product.discount }}%
                </p>
              </div>
            {% endif %}
            <a href="
              {% if product.url %}
                {{ product.url }}?currency={{ selected_currency.Name }}
              {% else %}
                {% url 'products:product' region.slug product.subcategory_slug product.slug %}?currency={{ selected_currency.Name }}
              {% endif %}
            ">
              <div class="img-box">
                <img
                  src="{{ product.image.url }}"
                  alt="{{ product.Name }}"
                  itemprop="image"
                />
              </div>
            </a>
            <div class="prod-desc" itemprop="description">
              <div class="card-top">
                <div class="prod-title">
                  <h3 class="h2-24-auto-bold cart-product-title" itemprop="name">{{ product.Name }}</h3>
                  {% if product.is_bouquet %}
                    <p class="p-16-auto-regular">Размер: {{ product.selected_size }}</p>
                  {% endif %}
                  <p class="p-16-auto-regular">Артикул: {{ product.sku }}</p>
                </div>
                <div class="card-btn">
                  <button class="delete-button icon remove-from-cart"></button>
                </div>
              </div>
              <div class="card-bottom">
                <div class="prod-price">
                  <div class="current-price">
                    <p class="p-16-auto-regular">Ціна:</p>
                    <p
                      class="h2-24-auto-bold red"
                      itemprop="offers"
                      itemscope
                      itemtype="http://schema.org/Offer"
                    >
                      <span itemprop="price">
                        {% if product.discount %}
                          {{ product.new_price }}
                        {% else %}
                          {{ product.unit_price }}
                        {% endif %}
                      </span>
                      <span
                        itemprop="priceCurrency"
                        content="
                          {{ selected_currency.Name }}
                        "
                      >
                        {{ selected_currency.symbol }}
                      </span>
                    </p>
                  </div>
                  {% if product.discount %}
                    <div class="old-price">
                      <p
                        class="p-16-auto-medium grey"
                        itemprop="offers"
                        itemscope
                        itemtype="http://schema.org/Offer"
                      >
                        <span itemprop="price">{{ product.unit_price }}</span>
                        <span
                          itemprop="priceCurrency"
                          content="
                            {{ selected_currency.Name }}
                          "
                        >
                          {{ selected_currency.symbol }}
                        </span>
                      </p>
                    </div>
                  {% endif %}
                  </div>
                  {% include 'core_components/counter.html' %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

      <!-- CART CONTROLS -->
      <div class="cart-controls-container">
        <div class="cart-controls-totalprice">
          <p class="p-16-auto-regular">Разом</p>
          <p class="h2-24-auto-bold red">
            <span class="cart-total-price">{{ cart_grand_total_price }}</span>
            {{ selected_currency.symbol }}
          </p>
        </div>
        <a 
          href="{% url 'main_page:mainpage-view' region.slug %}?currency={{ selected_currency.Name }}" 
          class="p-16-auto-regular red"
        >
          Продовжити покупки
        </a>
      </div>
      
      <a
        href="{% url 'orders:checkout' region.slug %}?currency={{ selected_currency.Name }}"
        class="button-main-text p-16-auto-bold cart-order-button"
      >
        Оформити замовлення
      </a>
    </section>

    <!--SUGGESTED SECTION-->
    <section class="slider-for-cards m-b-60">
      <div class="slider-for-cards-container">
        <div class="title-box m-b-70">
          <h4 class="h1-42-auto-bold">Пропонуємо додати</h4>
        </div>
        <div class="swiper">
          <div class="swiper__inner">
            <div class="swiper-container swiper2">
              <div class="slider2 swiper-wrapper">
                <div class="slide2 swiper-slide">
                  {% for product in suggested_products %}
                    {% include 'core_components/cardXlForSlider.html' %}
                    {% if forloop.counter|divisibleby:3 %}
                      </div>
                      <div class="slide2 swiper-slide">
                    {% endif %}
                  {% endfor %}
                </div>
              </div>
              <div class="swiper-pagination"></div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- MODALS -->

    <!-- MODAL-CALL-BACK -->
    {% include 'core_components/callBackModal.html' %}

    <!-- MODAL-USER-LOCATION -->
    {% include 'core_components/locationModal.html' %}

    <!-- MODAL-QUICK-ORDER -->
    {% include 'core_components/quickOrderModal.html' %}

    <!-- SOCIALS BUTTONS -->
    {% include 'core_components/buttons.html' %}
  </main>

  <!-- FOOTER -->
  {% include 'core_components/footer.html' %}

  <!-- SCRIPT`S -->

  <!-- BOOTSTRAP-BUNDLE-MIN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- AXIOS -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

  <!-- TEL FLAGS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/intlTelInput.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/css/intlTelInput.css" rel="stylesheet" />

  <!-- Places в Maps JavaScript API -->
  <script src="{% static 'scripts/locationModal.js' %}"></script>

  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5i5JJfxtMemi02YamAeiMa1FqYbOqCQA&libraries=places&language=en&callback=initAutocomplete" async defer>
  </script>

  <!-- OWN JS CODE -->
  <script src="{% static 'scripts/swiper832.js' %}"></script>
  <script src="{% static 'scripts/header.js' %}"></script>
  <script src="{% static 'scripts/common.js' %}"></script>
  <script src="{% static 'cart/index.js' %}"></script>
  <script src="{% static 'scripts/sliderForCards.js' %}"></script>
  <script src="{% static 'scripts/sideButtons.js' %}"></script>
  <script src="{% static 'scripts/quickOrderModal.js' %}"></script>
  <script src="{% static 'scripts/callBackModal.js' %}"></script>
  <script src="{% static 'scripts/addToCart.js' %}"></script>
  <script src="{% static 'scripts/removeFromCart.js' %}"></script>
  <script src="{% static 'scripts/counter.js' %}"></script>
</body>

</html>