cart/urls.py
"""Urls list for 'userprofile' app."""

from django.urls import path

from .views import CartView

app_name = "cart"

urlpatterns = [
    path("<slug:region_slug>/cart/", CartView.as_view(), name="cart"),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("location.urls")),
    path("", include("orders.urls")),
    path("", include("feedback.urls")),
    path("", include("cart.urls")),
    path("", include("mainpage.urls")),
    path("", include("fillers.urls")),
    path("catalogue/", include("catalogue.urls")),
    path("delivery_and_payment/", include("delivery_and_payment.urls")),
    path("reviews/", include("reviews.urls")),
    path("product/", include("products.urls")),
    path("zoho-token/", include("zoho_token.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
"""Orders urls."""
from django.urls import path

from .views import CheckoutView, IndividualOrders, OrdersList, QuickOrders

app_name = "orders"

urlpatterns = [
    path(
        "individual-orders/",
        IndividualOrders.as_view(),
        name="individual-order",
    ),
    path(
        "quick-orders/",
        QuickOrders.as_view(),
        name="quick-order",
    ),
    path("<slug:region_slug>/checkout/", CheckoutView.as_view(), name="checkout"),
    path("<slug:region_slug>/orders/", OrdersList.as_view(), name="orders-list"),
]

orders/forms.py
"""Contains form for checkout view."""

import json

import phonenumbers
from django import forms
from django.core.exceptions import ValidationError

from async_forms.async_forms import AsyncForm

from .inputs import CheckboxHiddenInput


class AsyncCheckoutForm(AsyncForm):
    """Form for handling checkout information."""

    customer_phone_number = forms.CharField(
        max_length=25,
        widget=forms.HiddenInput(
            {
                "class": "order-tel-hidden",
            }
        ),
    )
    customer_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            {
                "class": "p-16-auto-regular darck-gray input-text order-customer-name",
                "placeholder": "Ім’я та прізвище",
            }
        ),
    )
    customer_email = forms.EmailField(
        max_length=120,
        widget=forms.EmailInput(
            {
                "class": "p-16-auto-regular darck-gray input-text order-customer-email",
                "placeholder": "Email",
            }
        ),
        required=False,
    )

    recipient_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            {
                "class": "p-16-auto-regular darck-gray input-text order-recipient-name",
                "placeholder": "Ім’я одержувача ...",
            }
        ),
        required=False,
    )
    recipient_phone_number = forms.CharField(
        max_length=25,
        widget=forms.HiddenInput(
            {
                "class": "order-tel-hidden",
            }
        ),
        required=False,
    )

    is_anonym = forms.BooleanField(
        widget=forms.CheckboxInput(
            {"id": "switchAnonym"},
        ),
        initial=False,
        required=False,
    )
    is_surprise = forms.BooleanField(
        widget=forms.CheckboxInput({"id": "switchIsSurprise"}), initial=False, required=False
    )
    ask_recipient_address = forms.BooleanField(
        widget=forms.CheckboxInput({"id": "switchAddress"}), initial=False, required=False
    )
    recipient_is_customer = forms.BooleanField(
        widget=CheckboxHiddenInput(
            {
                "class": "p-16-auto-medium darck-gray input-text",
                "id": "isRecipientCustomer",
            },
        ),
        initial=False,
        required=False,
    )
    recipient_is_not_customer = forms.BooleanField(
        widget=CheckboxHiddenInput(
            {
                "class": "p-16-auto-medium darck-gray input-text",
                "id": "isRecipientNotCustomer",
            },
        ),
        initial=True,
        required=False,
    )

    country = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            {
                "class": "p-16-auto-regular darck-gray input-text order-country",
                "placeholder": "Країна ...",
                "id": "autocompleteCountry",
            }
        ),
        required=False,
    )
    region = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            {
                "class": "p-16-auto-regular darck-gray input-text order-region",
                "placeholder": "Область ...",
                "id": "autocompleteRegion",
            }
        ),
        required=False,
    )
    city = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            {
                "class": "p-16-auto-regular darck-gray input-text order-city",
                "placeholder": "Місто ...",
                "id": "autocompleteCity",
            }
        ),
        required=False,
    )
    address = forms.CharField(
        max_length=80,
        widget=forms.HiddenInput(
            {
                "class": "order-address",
            }
        ),
        required=False,
    )
    flat = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            {
                "class": "p-16-auto-regular darck-gray input-text order-flat",
                "placeholder": "Поміщення ...",
            }
        ),
        required=False,
    )
    date = forms.DateField(
        widget=forms.DateInput(
            {"type": "date", "class": "p-16-auto-regular darck-gray input-text order-date"}
        ),
    )

    postcard = forms.CharField(
        max_length=1000,
        required=False,
        widget=forms.Textarea(
            {"class": "input-text order-postcard", "placeholder": "Текст листівки ..."}
        ),
    )
    selected_currency = forms.CharField(widget=forms.HiddenInput())

    async def async_clean(self):
        """To perform asynchronous form validation.

        This method is responsible for performing additional validation checks
        beyond the standard synchronous clean() method. It is designed for
        handling asynchronous validation, such as making database queries or
        external API calls.

        Returns:
            dict: A dictionary containing the cleaned form data after validation.

        Raises:
            ValidationError: If any validation error occurs, a
                ValidationError is raised with an appropriate error message.

        Example:
            The method checks various conditions related to recipient information,
            delivery address, and other form fields, raising ValidationError if
            any inconsistency is detected.
        """
        cleaned_data = await super().async_clean()
        if not (
            cleaned_data["recipient_is_customer"] ^ cleaned_data["recipient_is_not_customer"]
        ):
            raise ValidationError(
                "Fields 'recipient is customer', 'recipient is not customer' checked/unchecked."
            )
        if cleaned_data["recipient_is_customer"] and (
            cleaned_data["recipient_name"] or cleaned_data["recipient_phone_number"]
        ):
            raise ValidationError(
                "Fields 'recipient name' and 'recipient phone number "
                "can't be filled together with 'is customer recipient' field."
            )

        elif cleaned_data["recipient_is_not_customer"] and (
            not cleaned_data["recipient_name"] or not cleaned_data["recipient_phone_number"]
        ):
            raise ValidationError(
                """Fields 'recipient name' and 'recipient phone number'
                both must be filled together with 'is customer recipient' field."""
            )
        if not cleaned_data["ask_recipient_address"] and (
            not cleaned_data.get("country")
            or not cleaned_data.get("region")
            or not cleaned_data.get("city")
            or not cleaned_data.get("address")
            or not cleaned_data.get("flat")
        ):
            raise ValidationError(
                f"You address isn't specified and 'ask recipient address' option " f"unchecked."
            )
        if not cleaned_data.get("date"):
            raise ValidationError("Delivery date isn't specified.")

        if cleaned_data.get("address"):
            try:
                cleaned_data["address"] = json.loads(cleaned_data["address"])
            except json.JSONDecodeError:
                raise ValidationError("Server error occured while validating address.")
        return cleaned_data

    def clean_recipient_phone_number(self):
        """
        Clean and parse the recipient's phone number.

        Returns:
            int: The cleaned and parsed recipient's phone number.
        """
        if phone_number := self.cleaned_data.get("recipient_phone_number"):
            return self._parse_phone_number(phone_number)
        return phone_number

    def clean_customer_phone_number(self):
        """
        Clean and parse the buyer's phone number.

        Returns:
            int: The cleaned and parsed buyer's phone number.
        """
        return self._parse_phone_number(self.cleaned_data.get("customer_phone_number"))

    @staticmethod
    def _parse_phone_number(phone_number: str):
        """
        Parse and validate a phone number using phonenumbers library.

        Args:
            phone_number (str): The phone number to parse and validate.

        Returns:
            int: The parsed and validated phone number.

        Raises:
            ValidationError: If the phone number has an invalid format.
        """
        z = phonenumbers.parse(phone_number, keep_raw_input=True)
        if not phonenumbers.is_valid_number(z):
            raise ValidationError("Wrong phone number format.")
        return phonenumbers.format_number(z, phonenumbers.PhoneNumberFormat.E164)

orders/templates/orders/checkout.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Оформление заказа</title>

  <!-- FAVICON -->

  <link rel="shortcut icon" href="{% static 'mainpage/favicon.svg' %}" type="image/x-icon" />

  <!-- FOR-PHONE-INPUT -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

  <!-- BOOTSTRAP -->

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

  <!-- SITE-STYLE -->

  <link rel="stylesheet" href="{% static 'styles/swiper832.min.css' %}">
  <link rel="stylesheet" href="{% static 'styles/common.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/header.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/footer.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/sideButtons.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/counter.css' %}">
  <link rel="stylesheet" href="{% static 'styles/callBackModal.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/cardXlForSlider.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/cardLforCart.css' %}" />
  <link rel="stylesheet" href="{% static 'orders/styles.css' %}" />
  
</head>

<body>
  <!-- HEADER -->
  {% include 'core_components/header.html' %}

  <main>
    <form class="container order-container" method="post" action="{% url 'orders:checkout' region.slug %}">
      {% csrf_token %}
      <div class="order-top-container">
        <!-- ORDER SETTING SECTION -->
        <section class="order-setting-container">
          <!-- TITLE -->
          <h2 class="h2-24-auto-medium">Оформлення замовлення</h2>
          <!-- STEP 1 -->
          <div>
            <div class="m-b-40 order-setting-subtitle-container">
              <span class="order-setting-number">1</span>
              <span class="h2-24-auto-medium order-setting-subtitle">Ваші дані</span>
            </div>
            <div class="order-separator"></div>
          </div>

          <input type="hidden" name="selected_currency" id="id_selected_currency" value="{{ selected_currency.Name }}">
          <div class="order-input-group">
            <div class="content">
              <div class="form-group">
                <input type="tel" class="form-control tel order-tel" name="customer_phone_number_mask" inputmode="tel"
                  value="" required />
                {{ form.customer_phone_number }}
              </div>
              {{ form.customer_name }}
              {{ form.customer_email }}
            </div>

            <div class="order-switch-anonim">
              <div class="toggle-switch">
                {{ form.is_anonym }}
                <label for="switchAnonym"></label>
              </div>
              <label for="switchAnonym">Відправити замовлення анонімно</label>
            </div>
          </div>

          <!-- STEP 2 -->
          <div>
            <div class="m-b-25 order-setting-subtitle-container">
              <span class="order-setting-number">2</span>
              <span class="h2-24-auto-medium order-setting-subtitle">Доставка</span>
            </div>
            <div class="order-separator"></div>
          </div>

          <div>
            <div class="content">
              <input type="checkbox" id="orderByCourier" class="order-by-courier" hidden />
              <label for="orderByCourier" class="button-main-text p-16-auto-medium m-b-40">
                Кур’єром
              </label>

              <div class="m-b-40 order-switch-specify">
                <div class="toggle-switch">
                  {{ form.ask_recipient_address }}
                  <label for="switchAddress"></label>
                </div>
                <label for="switchAddress">Уточнити адресу у отримувача</label>
              </div>

              <div class="order-address-container order-input-group">
                <input type="text" class="p-16-auto-regular darck-gray input-text order-address-mask"
                  name="address_mask" id="autocompleteAddress" placeholder="Виберіть адресу" />
                {{ form.address }}
                {{ form.flat }}
                {{ form.city }}
                {{ form.region }}
                {{ form.country }}
                <div class="order-date-input">
                  {{ form.date }}
                  <input type="text" class="p-16-auto-regular darck-gray input-text order-date-mask" name="date_mask"
                    placeholder="Дата" />
                </div>
              </div>
            </div>
          </div>

          <div class="order-recipient-container order-recipient-group">
            {{ form.recipient_is_customer }}
            <label for="isRecipientCustomer" class="p-16-auto-medium">Я одержувач</label>
            {{ form.recipient_is_not_customer }}
            <label for="isRecipientNotCustomer" class="p-16-auto-medium">У подарунок</label>
          </div>

          <div class="order-address-container order-input-group order-present">
            {{ form.recipient_name }}
            <div class="form-group">
              <input type="tel" class="form-control tel order-tel order-recipient-phone"
                name="recipient_phone_number_mask" inputmode="tel" value="" required />
              {{ form.recipient_phone_number }}
            </div>
          </div>

          <div class="order-switch-surprice order-present">
            <div class="toggle-switch">
              {{ form.is_surprise }}
              <label for="switchIsSurprise"></label>
            </div>
            <label for="switchIsSurprise">Виконати доставку сюрпризом (без попереднього дзвінка)</label>
          </div>

          <!-- STEP 3 -->
          <div>
            <div class="m-b-25 order-setting-subtitle-container">
              <span class="order-setting-number">3</span>
              <span class="h2-24-auto-medium order-setting-subtitle">Листівка</span>
            </div>
            <div class="order-separator"></div>
          </div>

          <div class="order-postcard-container">
            <p class="p-16-auto-medium">Листівка</p>
            {{ form.postcard }}
          </div>

          <!-- STEP 4 -->
          <div id="orderSlider">
            <div class="m-b-25 order-setting-subtitle-container">
              <span class="order-setting-number">4</span>
              <span class="h2-24-auto-medium order-setting-subtitle">Подарунок</span>
            </div>
            <div class="order-separator"></div>
          </div>

          <!-- SLIDER
          <div class="slider-for-cards m-b-60">
            <div class="slider-for-cards-container">
              <div class="slider-product-container">
                <div class="slide_viewer">
                  <div class="slide_group our-bestsellers-slider">

                    <div class="slide-card-container">
                      {% for product in suggested_products %}
                        {% include 'core_components/cardXlForSliderWithoutButton.html' %}

                        {% if forloop.counter|divisibleby:2 %}
                          </div>
                          <div class="slide-card-container">
                        {% endif %}
                      {% endfor %}
                    </div>

                  </div>
                </div>
                <a href="#orderSlider" class="slide_buttons"></a>
              </div>
            </div>
          </div> -->

          <div class="swiper">
            <div class="swiper__inner">
              <div class="swiper-container swiper2">
                <div class="slider2 swiper-wrapper">
                  <div class="slide2 swiper-slide">
                    {% for product in suggested_products %}
                      {% include 'core_components/cardXlForSliderWithoutButton.html' %}
                      {% if forloop.counter|divisibleby:2 %}
                        </div>
                        <div class="slide2 swiper-slide">
                      {% endif %}
                    {% endfor %}
                  </div>
                </div>
                <div class="swiper-pagination"></div>
              </div>
            </div>
          </div>

          <div id="orderCardsContainer" class="order-cards-container">

          </div>

          <!-- STEP 5 -->
          <div>
            <div class="m-b-25 order-setting-subtitle-container">
              <span class="order-setting-number">5</span>
              <span class="h2-24-auto-medium order-setting-subtitle">Оплата</span>
            </div>
            <div class="order-separator"></div>
          </div>

          <div class="order-paymentTypes-container">
            <div>
              <div class="order-paymentType">
                <input class="form-check-input" type="radio" name="paymentType" id="paymentType-0" checked />
                <label for="paymentType-0" class="p-16-auto-regular">Liqpay</label>
              </div>
              <label for="paymentType-0" class="order-paymentType-logo">Logo 1</label>
              <label for="paymentType-0" class="p-14-auto-regular order-paymentType-caption">
                Після оформлення замовлення ви будете перенаправлені на сторінку оплати
              </label>
            </div>

            <div>
              <div class="order-paymentType">
                <input class="form-check-input" type="radio" name="paymentType" id="paymentType-1" />
                <label for="paymentType-1" class="p-16-auto-regular">Portmone</label>
              </div>
              <label for="paymentType-1" class="order-paymentType-logo">Logo 2</label>
              <label for="paymentType-1" class="p-14-auto-regular order-paymentType-caption">
                Після оформлення замовлення ви будете перенаправлені на сторінку оплати
              </label>
            </div>
          </div>
        </section>

        <!-- ORDER SELECTED SECTION -->
        <section class="order-selected">
          <div class="m-b-40 order-selected-title-container">
            <h2 class="h2-24-auto-medium">Ваше замовлення</h2>
            <a href="{% url 'cart:cart' region.slug %}?currency={{ selected_currency.Name }}"
              class="p-14-auto-regular red">Редагувати</a>
          </div>

          <div class="m-b-40 order-selected-cards-container">
            {% for product in cart_products %}
              {% include 'core_components/cardSforCheckout.html' %}
            {% endfor %}
          </div>

          <div class="order-selected-totalprice">
            <p class="p-16-auto-regular">Разом:</p>
            <p class="h2-24-auto-medium red">
              <span id="cartTotalPrice" class="cart-total-price">{{ cart_grand_total_price }}</span>
              <span>{{ selected_currency.symbol }}</span>
            </p>
          </div>
        </section>
      </div>

      <!-- BOTTOM SECTION -->
      <section class="order-bottom-container">
        <button type="submit" class="button-main-text p-16-auto-bold order-button disabled-button" disabled>
          Оформити замовлення
        </button>
        <div class="order-terms">
          <input class="form-check-input" type="radio" name="orderTerms" id="orderTerms" />
          <label for="orderTerms" class="p-16-auto-regular" required>
            Я Згоден(а) з умовами договору публічної оферти.
          </label>
        </div>
      </section>
    </form>

    <!-- MODALS -->
    <!-- MODAL-CALL-BACK -->
    {% include 'core_components/callBackModal.html' %}
    <!-- MODAL-USER-LOCATION -->
    {% include 'core_components/locationModal.html' %}

    <!-- MODAL-QUICK-ORDER -->
    {% include 'core_components/quickOrderModal.html' %}

    <!-- SOCIALS BUTTONS -->
    {% include 'core_components/buttons.html' %}
  </main>

  <!-- FOOTER -->
  {% include 'core_components/footer.html' %}

  <!-- SCRIPT`S -->

  <!-- BOOTSTRAP-BUNDLE-MIN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- AXIOS -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

  <!-- TEL FLAGS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/intlTelInput.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/css/intlTelInput.css" rel="stylesheet" />

  <!-- Places в Maps JavaScript API -->
  <script src="{% static 'scripts/locationModal.js' %}"></script>

  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5i5JJfxtMemi02YamAeiMa1FqYbOqCQA&libraries=places&language=en&callback=initAutocomplete"
    async defer>
    </script>

  <!-- OWN JS CODE -->
  <script src="{% static 'scripts/swiper832.js' %}"></script>
  <script src="{% static 'scripts/header.js' %}"></script>
  <script src="{% static 'scripts/common.js' %}"></script>
  <script src="{% static 'orders/scripts.js' %}"></script>
  <script src="{% static 'cart/index.js' %}"></script>
  <script src="{% static 'scripts/sliderForCards.js' %}"></script>
  <script src="{% static 'scripts/sideButtons.js' %}"></script>
  <script src="{% static 'scripts/callBackModal.js' %}"></script>
  <script src="{% static 'scripts/counter.js' %}"></script>
  <script src="{% static 'scripts/removeFromCarts.js' %}"></script>
  <script src="{% static 'scripts/addToCarts.js' %}"></script>
</body>

</html>

orders/templates/orders/ordersList.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Оформление заказа</title>

    <!-- FAVICON -->

    <link rel="shortcut icon" href="{% static 'mainpage/favicon.svg' %}" type="image/x-icon" />

    <!-- FOR-PHONE-INPUT -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

    <!-- BOOTSTRAP -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

    <!-- SITE-STYLE -->

    <link rel="stylesheet" href="{% static 'styles/common.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/header.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/footer.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/sideButtons.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/callBackModal.css' %}" />
    <link rel="stylesheet" href="{% static 'orders/orderedPage.css' %}">
    <link rel="stylesheet" href="{% static 'styles/cartOrdersSwitch.css' %}">
</head>

<body>
    <!-- HEADER -->
    {% include 'core_components/header.html' %}

    <main>
        <div class="container">
            {% include 'core_components/cartOrdersSwitch.html' %}

            <div class="ordered-container">
                {% for order in orders %}
                    <div class="ordered-order">
                        <div class="ordered-property-number-mobile">
                            <p class="p-16-auto-regular">Номер замовлення</p>
                            <p class="h2-24-auto-medium black">{{ order.number }}</p>
                        </div>
                        <div class="ordered-props">
                            <div class="ordered-property ordered-property-number">
                                <p class="p-16-auto-regular">Номер замовлення</p>
                                <p class="h2-24-auto-medium black">{{ order.number }}</p>
                            </div>
                            <div class="ordered-property">
                                <p class="p-16-auto-regular">Дата</p>
                                <p class="h2-24-auto-medium black">{{ order.target_delivery_date }}</p>
                            </div>
                            <div class="ordered-property">
                                <p class="p-16-auto-regular">Сума</p>
                                <p class="h2-24-auto-medium red">{{ order.grand_total }}{{ order.selected_currency.symbol }} </p>
                            </div>
                            <div class="ordered-property">
                                <p class="p-16-auto-regular">Статус</p>
                                {% if order.status.value == orders_statutes.pending %}
                                    <p class="h2-24-auto-medium dark-orange">{{ order.status.value }}</p>
                                {% elif order.status.value == orders_statutes.return %}
                                    <p class="h2-24-auto-medium medium-red">{{ order.status.value }}</p>
                                {% elif order.status.value == orders_statutes.in_progress %}
                                    <p class="h2-24-auto-medium medium-blue">{{ order.status.value }}</p>
                                {% elif order.status.value == orders_statutes.delivered %}
                                    <p class="h2-24-auto-medium light-green">{{ order.status.value }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="ordered-products">
                            {% for product in order.products %}
                                <div class="ordered-product">
                                    <div class="ordered-product-name">
                                        <p class="h2-24-auto-medium">{{ product.name }}</p>
                                        <p class="p-16-auto-regular">Артикул {{ product.sku }}</p>
                                    </div>
                                    <div class="ordered-product-quantity">
                                        <p class="p-16-auto-regular">Кількість</p>
                                        <p class="h2-24-auto-medium black">{{ product.amount }}</p>
                                    </div>
                                    <div class="ordered-product-sum">
                                        <p class="p-16-auto-regular">Сума</p>
                                        <p class="h2-24-auto-medium red">{{ product.price }}{{ order.selected_currency.symbol }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>

        <!-- MODALS -->
        <!-- MODAL-CALL-BACK -->
        {% include 'core_components/callBackModal.html' %}
        <!-- MODAL-USER-LOCATION -->
        {% include 'core_components/locationModal.html' %}

        <!-- MODAL-QUICK-ORDER -->
        {% include 'core_components/quickOrderModal.html' %}

        <!-- SOCIALS BUTTONS -->
        {% include 'core_components/buttons.html' %}
    </main>

    <!-- FOOTER -->
    {% include 'core_components/footer.html' %}

    <!-- SCRIPT`S -->

    <!-- BOOTSTRAP-BUNDLE-MIN -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- AXIOS -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <!-- TEL FLAGS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/intlTelInput.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/css/intlTelInput.css" rel="stylesheet" />

    <!-- Places в Maps JavaScript API -->
    <script src="{% static 'scripts/locationModal.js' %}"></script>

    <script
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5i5JJfxtMemi02YamAeiMa1FqYbOqCQA&libraries=places&language=en&callback=initAutocomplete"
        async defer>
        </script>

    <!-- OWN JS CODE -->
    <script src="{% static 'scripts/header.js' %}"></script>
    <script src="{% static 'scripts/common.js' %}"></script>
    <script src="{% static 'scripts/sideButtons.js' %}"></script>
    <script src="{% static 'scripts/callBackModal.js' %}"></script>
    <script src="{% static 'scripts/counter.js' %}"></script>
</body>

</html>