cart/urls.py
"""Urls list for 'userprofile' app."""

from django.urls import path

from .views import CartView

app_name = "cart"

urlpatterns = [
    path("<slug:region_slug>/cart/", CartView.as_view(), name="cart"),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("location.urls")),
    path("", include("orders.urls")),
    path("", include("feedback.urls")),
    path("", include("cart.urls")),
    path("", include("mainpage.urls")),
    path("", include("fillers.urls")),
    path("catalogue/", include("catalogue.urls")),
    path("delivery_and_payment/", include("delivery_and_payment.urls")),
    path("reviews/", include("reviews.urls")),
    path("product/", include("products.urls")),
    path("zoho-token/", include("zoho_token.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

location/urls.py
"""Feedback urls."""
from django.urls import path

from .views import LocationView

app_name = "location"

urlpatterns = [
    path("location/", LocationView.as_view(), name="location-view"),
]

mainpage/urls.py
"""Urls list for 'mainpage' app."""
from django.urls import path

from .views import MainPageView

app_name = "main_page"

urlpatterns = [
    path("", MainPageView.as_view(), name="main_page"),
    path("<slug:region_slug>/", MainPageView.as_view(), name="mainpage-view"),
]

orders/urls.py
"""Orders urls."""
from django.urls import path

from .views import CheckoutView, IndividualOrders, OrdersList, QuickOrders

app_name = "orders"

urlpatterns = [
    path(
        "individual-orders/",
        IndividualOrders.as_view(),
        name="individual-order",
    ),
    path(
        "quick-orders/",
        QuickOrders.as_view(),
        name="quick-order",
    ),
    path("<slug:region_slug>/checkout/", CheckoutView.as_view(), name="checkout"),
    path("<slug:region_slug>/orders/", OrdersList.as_view(), name="orders-list"),
]

products/urls.py
"""Urls for 'products' app."""

from django.urls import path

from .views import ProductSearchView, ProductView

app_name = "products"

urlpatterns = [
    path(
        "<slug:region_slug>/",
        ProductSearchView.as_view(),
    ),
    path(
        "<slug:region_slug>/<slug:subcategory_slug>/<slug:product_slug>/",
        ProductView.as_view(),
        name="product",
    ),
]

coreStaticFiles/templates/core_components/buttons.html
<!-- SOCIALS BUTTONS -->
<div class="cta-btn-group">
  <div class="contact-us">
    <button id="open-cta" class="cta-button">
      <span class="icon"></span>
    </button>
    <div class="contact-us-btn-group">
      <a href="{{ region.viber_link }}" target="_blank" class="contact-us-btn viber icon"></a>
      <a href="{{ region.telegram_link }}" target="_blank" class="contact-us-btn telegram icon"></a>
      <a href="{{ region.whatsapp_link }}" target="_blank" class="contact-us-btn whatsapp icon"></a>
    </div>
  </div>
  <a id="scroll-up" class="cta-button" href="#"><span class="icon"></span></a>
</div>

coreStaticFiles/templates/core_components/callBackModal.html
<!-- MODAL-CALL-BACK -->
<div
  class="modal fade callBackModal" 
  id="callBackModal"
  tabindex="-1"
  aria-labelledby="callBackModalLabel"
  aria-hidden="true"
>

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close icon" data-bs-dismiss="modal" aria-label="Close">
          
        </button>
      </div>
      <div class="modal-body">
        <h5 class="h2-24-auto-bold" id="callBackModalLabel">
          Зворотній дзвінок
        </h5>
        <div class="input-tell-container">
          <form action="#" method="post" class="call-back-modal-form">
            {% csrf_token %}
            <div class="content">
              <input
                type="text"
                class="p-16-auto-regular darck-gray input-text call-back-modal-name"
                name="name"
                placeholder="Ваше ім’я"
              />
              <div class="form-group">
                <input
                  type="tel"
                  class="form-control tel call-back-modal-tel"
                  name="leyka_donor_phone"
                  inputmode="tel"
                  value=""
                />
              </div>
            </div>
            <button class="button-main-text disabled-button p-16-auto-bold call-back-modal-button" type="submit"
              value="Отправить" disabled>
              Відправити
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

coreStaticFiles/templates/core_components/cardLforCart.html
<div class="card-xs" href="{{ product.url }}">
    <div class="img-box">
      <img src="{{ product.image.url }}" alt="{{ product.Name }}" />
    </div>
    <div class="prod-desc">
      <div class="card-top">
        <div class="prod-title">
          <h3 class="h2-24-auto-medium">
          {{ product.Name }}
          </h3>
        </div>
      </div>
      <div class="card-bottom">
        <div class="prod-price">
          
          <div class="current-price">
            <p class="h2-24-auto-medium red">
              {% if product.new_price %}
                {{ product.new_price }} {{ selected_currency.symbol }}
              {% else %}
                {{ product.unit_price }} {{ selected_currency.symbol }}
              {% endif %}
            </p>
          </div>

          {% if product.new_price %}
            <div class="old-price">
              <p class="p-16-auto-medium grey">
                  {{ product.unit_price }}
              </p>
            </div>
          {% endif %}

          <div class="counter">
            <button class="decrement icon grey"></button>
            <span class="count h2-24-auto-regular">{{ product.cart_amount }}</span>
            <button class="increment icon red"></button>
          </div>
        </div>
      </div>
    </div>
  </div>

coreStaticFiles/templates/core_components/cardSforCheckout.html
<div class="card-s">
  <div class="img-box">
    <img class="quick-order-modal-card-img" src="{{ product.image.url }}" alt="{{ product.Name }}" />
  </div>
  <div class="prod-desc">
    <div class="card-top">
      <div class="prod-title">
        <h3 class="p-16-auto-medium quick-order-modal-card-title">{{ product.Name }}</h3>
        <p class="p-14-auto-regular quick-order-modal-card-article">Артикул: {{ product.sku }}</p>
        {% if product.is_bouquet %}
          <p class="p-14-auto-regular quick-order-modal-card-size">Размер: {{ product.selected_size }}</p>
        {% endif %}
      </div>
    </div>
    <div class="card-bottom">
      <div class="prod-price">
        <div class="current-price">
          <p class="p-14-auto-regular">Ціна:</p>
          <p class="p-16-auto-medium red quick-order-modal-card-price">
            {% if product.new_price %}
              {{ product.new_price }} {{ selected_currency.symbol }}
            {% else %}
              {{ product.unit_price }} {{ selected_currency.symbol }}
            {% endif %}
          </p>
        </div>

        {% if product.new_price %}
          <div class="old-price">
            <p class="p-14-auto-medium grey quick-order-modal-card-old-price">
              {{ product.unit_price }} {{ selected_currency.symbol }}
            </p>
          </div>
        {% endif %}
      </div>
      <div class="product-count" id="counter">
        <p class="p-14-auto-medium">{{ product.cart_amount }} шт.</p>
      </div>
    </div>
  </div>
</div>

coreStaticFiles/templates/core_components/cardXlForSlider copy.html
/home/code/Documents/BFFTP/src/coreStaticFiles/templates/core_components/cardXlForSlider copy.html

coreStaticFiles/templates/core_components/cardXlForSlider.html
<div
  class="card-xl product-card"
  data-product-id="{{ product.id }}"
  data-product-new-price="{{ product.new_price }}"
  data-product-unit-price="{{ product.unit_price }}"
  data-is-added="{{ product.is_in_cart }}"
  data-is-bouquet="{{ product.is_bouquet }}"
  data-region="{{ region.slug }}"
  itemscope
  itemtype="http://schema.org/Product"
>
  {% if product.discount %}
    <div class="discount">
      <p class="p-16-auto-medium white">
        {{ product.discount }}%
      </p>
    </div>
  {% endif %}
  <a href="
    {% if product.url %}
      {{ product.url }}?currency={{ selected_currency.Name }}
    {% else %}
      {% url 'products:product' region.slug product.subcategory_slug product.slug %}?currency={{ selected_currency.Name }}
    {% endif %}
  ">
 
    <div class="img-box">
      <img
        src="{{ product.image.url }}"
        alt="{{ product.Name }}"
        itemprop="image"
      />
    </div>
  
    <div class="prod-desc" itemprop="description">
      <div class="prod-title">
        <h3 class="h2-24-auto-bold" itemprop="name">
          {{ product.Name }}
        </h3>
      </div>
      <div class="prod-price">
        <div class="current-price">
          <p
            class="h2-24-auto-medium red"
            itemprop="offers"
            itemscope
            itemtype="http://schema.org/Offer"
          >
            <span itemprop="price">
              {% if product.discount %}
                {{ product.new_price }}
              {% else %}
                {{ product.unit_price }}
              {% endif %}
            </span>
            <span
              itemprop="priceCurrency"
              content="
                {{ selected_currency.Name }}
              "
            >
              {{ selected_currency.symbol }}
            </span>
          </p>
        </div>
        {% if product.discount %}
          <div class="old-price">
            <p
              class="p-16-auto-medium grey"
              itemprop="offers"
              itemscope
              itemtype="http://schema.org/Offer"
            >
              <span itemprop="price">{{ product.unit_price }}</span>
              <span
                itemprop="priceCurrency"
                content="
                  {{ selected_currency.Name }}
                "
              >
                {{ selected_currency.symbol }}
              </span>
            </p>
          </div>
        {% endif %}
      </div>
    </div>
  </a>
  <div class="card-btn">
    <Button
      type="button"
      class="button-main-text-icon p-16-auto-bold add-to-cart"
      data-region="{{ region.slug }}"
    >
      <span class="icon"></span>
      До кошика
    </Button>
    <Button
      type="button"
      class="button-main-text-icon p-16-auto-bold button-added-to-cart"
      hidden
    >
      <span class="icon"></span>
      У кошику
    </Button>
    <a
      class="p-16-auto-regular red quick-order-link"
      href="#"
      data-bs-toggle="modal"
      data-bs-target="#quickOrderModal"
      data-product-article="{{ product.sku }}"
      data-product-image="{{ product.image.url }}"
      data-product-title="{{ product.Name }}"
      data-product-discount-price="{{ product.new_price }}"
      data-product-price="
        {{ product.unit_price }}
      "
      data-product-id="{{ product.id }}"
      data-product-currency="{{ selected_currency.symbol }}"
      data-product-discount="{{ product.discount }}"
    >
      Швидке замовлення
    </a>
  </div>
</div>

coreStaticFiles/templates/core_components/cardXlForSliderWithoutButton.html
<div
  class="card-xl product-card add-to-cart"
  data-url="
  {% if product.url %}
    {{ product.url }}?currency={{ selected_currency.Name }}
  {% else %}
    {% url 'products:product' region.slug product.subcategory_slug product.slug %}?currency={{ selected_currency.Name }}
  {% endif %}
  "
  data-product-id="{{ product.id }}"
  data-product-new-price="{{ product.new_price }}"
  data-product-unit-price="{{ product.unit_price }}"
  data-product-price="{{ product.unit_price }}"
  data-product-currency="{{ selected_currency.symbol }}"
  data-product-discount-price="{{ product.new_price }}"
  data-product-discount="{{ product.discount }}"
  data-product-image="{{ product.image.url }}"
  data-product-article="{{ product.sku }}"
  data-product-title="{{ product.Name }}"
  data-is-bouquet="{{ product.is_bouquet }}"
  data-region="{{ region.slug }}"
  itemscope
  itemtype="http://schema.org/Product"
>
  {% if product.discount %}
    <div class="discount">
      <p class="p-16-auto-medium white">
        {{ product.discount }}%
      </p>
    </div>
  {% endif %}
 
    <div class="img-box">
      <img
        src="{{ product.image.url }}"
        alt="{{ product.Name }}"
        itemprop="image"
      />
    </div>
  <span class="add-to-cart-span">
    <div class="prod-desc" itemprop="description">
      <div class="prod-title">
        <h3 class="h2-24-auto-bold" itemprop="name">
          {{ product.Name }}
        </h3>
      </div>
      <div class="prod-price">
        <div class="current-price">
          <p
            class="h2-24-auto-medium red"
            itemprop="offers"
            itemscope
            itemtype="http://schema.org/Offer"
          >
            <span itemprop="price">
              {% if product.discount %}
                {{ product.new_price }}
              {% else %}
                {{ product.unit_price }}
              {% endif %}
            </span>
            <span
              itemprop="priceCurrency"
              content="
                {{ selected_currency.Name }}
              "
            >
              {{ selected_currency.symbol }}
            </span>
          </p>
        </div>
        {% if product.discount %}
          <div class="old-price">
            <p
              class="p-16-auto-medium grey"
              itemprop="offers"
              itemscope
              itemtype="http://schema.org/Offer"
            >
              <span itemprop="price">{{ product.unit_price }}</span>
              <span
                itemprop="priceCurrency"
                content="
                  {{ selected_currency.Name }}
                "
              >
                {{ selected_currency.symbol }}
              </span>
            </p>
          </div>
        {% endif %}
      </div>
    </div>
  </span>
</div>

coreStaticFiles/templates/core_components/cartOrdersSwitch.html
<div class="ordered-top-controls m-b-60">
    {% if is_cart %}
        <a class="h2-24-auto-medium link-button active-button" aria-disabled="true">Кошик</h2>
        <a href="{% url 'orders:orders-list' region.slug %}?currency={{ selected_currency.Name }}" class="h2-24-auto-medium link-button">Замовлення</a>
    {% else %}
        <a href="{% url 'cart:cart' region.slug %}?currency={{ selected_currency.Name }}" class="h2-24-auto-medium link-button">Кошик</a>
        <a class="h2-24-auto-medium link-button active-button" aria-disabled="true">Замовлення</a>
    {% endif %}
</div>

coreStaticFiles/templates/core_components/counter.html
<!-- COUNTER -->
<div class="counter">
  <button class="decrement icon grey"></button>
  <span class="count p-14-auto-medium">
    {% if product.cart_amount %}
      {{ product.cart_amount }}
    {% else %}
      1
    {% endif %}
  </span>
  <button class="increment icon red"></button>
</div>

coreStaticFiles/templates/core_components/footer.html
{% load static %}
<!-- FOOTER -->
<footer>
  <div class="container">
    <div class="footer">
      <div class="main-section">
        <div class="logo-block">
          <a class="logo-box" href="{% url 'main_page:mainpage-view' region.slug %}?currency={{ selected_currency.Name }}">
            <img src="{% static 'mainpage/img/logo.svg' %}" alt="Site Logo" />
          </a>

          <!-- <div class="contact-us">
            <a href="{{ region.facebook_link }}" class="icon contact-us-btn facebook"></a>
            <a href="{{ region.telegram_link }}" class="icon contact-us-btn telegram"></a>
            <a href="{{ region.whatsapp_link }}" class="icon contact-us-btn whatsapp"></a>
            <a href="{{ region.instagram_link }}" class="icon contact-us-btn instagram"></a>
          </div> -->
        </div>

        <div class="contacts">
          <div class="top-section">
            <h4 class="p-16-auto-medium">Контакти</h4>

            <div class="phone-section">
              <div class="phone-block">
                <h5 class="p-14-auto-light">Україна</h5>

                <ul class="numbers">
                  <li>
                    <a href="tel:{{ region.local_phone_number_1 }}"
                      class="button-main-text-icon p-16-auto-regular user-page-link red">
                      <span class="icon red"></span>
                      {{ region.local_phone_number_1 }}
                    </a>
                  </li>
                  <li>
                    <a href="tel:{{ region.local_phone_number_2 }}"
                      class="button-main-text-icon p-16-auto-regular user-page-link red">
                      <span class="icon red"></span>
                      {{ region.local_phone_number_2 }}
                    </a>
                  </li>
                </ul>
              </div>

              <div class="phone-block">
                <h5 class="p-14-auto-light">
                  Міжнародний
                </h5>

                <ul class="numbers">
                  <li>
                    <a href="tel:{{ region.international_phone_number }}"
                      class="button-main-text-icon p-16-auto-regular user-page-link red">
                      <span class="icon red"></span>
                      {{ region.international_phone_number }}
                    </a>
                  </li>
                </ul>
              </div>
            </div>

            <div class="email-section">
              <h4 class="p-14-auto-light">Пошта</h4>
              <div>
                <a href="mailto:bonnyflowers@gmail.com"
                  class="button-main-text-icon p-16-auto-regular user-page-link red">
                  <span class="icon red"></span>
                  {{ region.email }}
                </a>
              </div>
            </div>
          </div>
        </div>

        <div class="category">
          <h4 class="p-16-auto-medium">Категорії</h4>

          <div class="info">
            <a class="p-14-auto-light" href="">Доставка и оплата</a>
            <a class="p-14-auto-light" href="">Гарантии качества</a>
            <a class="p-14-auto-light" href="">Условия и положения</a>
          </div>
        </div>

        <div class="for-clients">
          <h4 class="p-16-auto-medium">Для клієнта</h4>

          <div class="info-block">
            <ul class="info">
              <li>
                <a class="p-14-auto-light" href="">
                  Доставка и оплата
                </a>
              </li>
              <li>
                <a class="p-14-auto-light" href="">
                  Гарантии качества
                </a>
              </li>
              <li>
                <a class="p-14-auto-light" href="">
                  Условия и положения
                </a>
              </li>
            </ul>

            <ul class="info">
              <li>
                <a class="p-14-auto-light" href="">
                  Отзывы
                </a>
              </li>
              <li>
                <a class="p-14-auto-light" href="">
                  О нас
                </a>
              </li>
              <li>
                <a class="p-14-auto-light" href="">
                  Блог
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-bottom">
        <div class="contact-us">
          <a href="{{ region.facebook_link }}" class="icon contact-us-btn facebook"></a>
          <a href="{{ region.telegram_link }}" class="icon contact-us-btn telegram"></a>
          <a href="{{ region.whatsapp_link }}" class="icon contact-us-btn whatsapp"></a>
          <a href="{{ region.instagram_link }}" class="icon contact-us-btn instagram"></a>
        </div>
        <p class="bottom-section all-rights-reserved">
          <span class="p-16-auto-regular red">© 2023 BonnyFlowers.com</span>
        </p>
      </div>
    </div>
  </div>
</footer>

coreStaticFiles/templates/core_components/locationModal.html
<div 
  class="modal fade userLocationModal" 
  id="userLocationModal" 
  tabindex="-1" 
  aria-labelledby="userLocationModal"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button 
          type="button" 
          class="btn-close icon" 
          data-bs-dismiss="modal" 
          aria-label="Close"
        >
          
        </button>
      </div>
      <div class="modal-body">
        <h5 class="h2-24-auto-bold" id="userLocationModalLabel">
          Місце розташування
        </h5>
        <div class="input-tell-container">
          <form method="get" action="{% url 'location:location-view' %}" class="location-form">
            <div class="content">
              <input
                type="text"
                class="p-16-auto-regular darck-gray input-text location-city"
                name="city"
                placeholder="Місто"
                id="autocompleteCityLocation"
                required
              />
              <input
                type="text"
                class="p-16-auto-regular darck-gray input-text location-region"
                name="region"
                placeholder="Штат/Регіон"
                id="autocompleteRegionLocation"
                required
              />
              <input
                type="text"
                class="p-16-auto-regular darck-gray input-text location-country"
                name="country"
                placeholder="Країна"
                id="autocompleteCountryLocation"
                required
              />
            </div>
            <button
              class="button-main-text p-16-auto-bold location-button disabled-button"
              type="submit"
              value="Отправить"
            >
              Відправити
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

coreStaticFiles/templates/core_components/notification.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang="uk">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{ title }}</title>

  <!-- FAVICON -->

  <link rel="shortcut icon" href="{% static 'mainpage/favicon.svg' %}" type="image/x-icon" />

  <!-- FOR-PHONE-INPUT -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

  <!-- BOOTSTRAP -->

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

  <!-- SITE-STYLE -->
  <link rel="stylesheet" href="{% static 'styles/common.css' %}">
  <link rel="stylesheet" href="{% static 'styles/sideButtons.css' %}">
</head>


  <main>
    <section class="container notification-container m-b-60">
      <div class="title-box notification-title">
        <h4 class="h1-42-auto-bold">{{ header }}</h4>
      </div>
      <p class="p-16-auto-regular notification-contant m-b-100">
        {{ message_top }}
          {% if spanned_message %}
            <span class="p-16-auto-medium red">{{ spanned_message }}</span>
          {% endif %}
        .
        <br>
        {{ message_bottom }}.
      </p>
      <a
        href="{{ redirect_url }}"
        class="button-main-text p-16-auto-bold cart-order-button"
      >
        {{ redirect_message }}
      </a>
    </section>

    <!-- SOCIALS BUTTONS -->
    {% include 'core_components/buttons.html' %}
  </main>


  <!-- SCRIPT`S -->

  <!-- BOOTSTRAP-BUNDLE-MIN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- AXIOS -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5i5JJfxtMemi02YamAeiMa1FqYbOqCQA&libraries=places&language=en&callback=initAutocomplete" async defer>
  </script>
  <script src="{% static 'scripts/sideButtons.js' %}"></script>
</body>

</html>

coreStaticFiles/templates/core_components/quickOrderModal.html
<!-- MODAL-QUICK-ORDER -->
<div class="modal fade quickOrderModal" id="quickOrderModal" tabindex="-1" aria-labelledby="quickOrderModal"
  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close icon" data-bs-dismiss="modal" aria-label="Close">
          
        </button>
      </div>
      <div class="modal-body">
        <h5 class="h2-24-auto-bold quick-order-modal-title" id="quickOrderModalLabel">
          Швидке Замовлення
        </h5>
        <!-- card-S -->
        <div class="card-s">
          <div class="img-box">
            <img class="quick-order-modal-card-img" src="" alt="name-of-this-flower" />
          </div>
          <div class="prod-desc">
            <div class="card-top">
              <div class="prod-title">
                <h3 class="p-16-auto-medium quick-order-modal-card-title">Назва квітки</h3>
                <p class="p-14-auto-regular quick-order-modal-card-article">Артикул: 2222</p>
              </div>
            </div>
            <div class="card-bottom">
              <div class="prod-price">
                <div class="current-price">
                  <p class="p-14-auto-regular">Ціна:</p>
                  <p class="p-16-auto-medium red quick-order-modal-card-price"></p>
                </div>
                <div class="old-price">
                  <p class="p-16-auto-medium grey quick-order-modal-card-old-price"></p>
                </div>
              </div>
              <div class="product-count" id="counter">
                <p class="p-14-auto-medium">1 шт.</p>
              </div>
            </div>
          </div>
        </div>

        <!-- MODAL-QUICK-ORDER form -->
        <div class="input-tell-container">
          <form action="#" method="post" class="quick-order-modal-form">
            {% csrf_token %}
            <div class="content">
              <!-- MODAL-QUICK-ORDER input name -->
              <input 
                type="text" 
                class="p-16-auto-regular darck-gray input-text quick-order-modal-name"
                name="name"
                placeholder="Ваше ім’я" 
              />
              <!-- MODAL-QUICK-ORDER input tel -->
              <div class="form-group">
                <input 
                  type="tel" 
                  class="form-control tel quick-order-modal-tel" 
                  name="leyka_donor_phone"
                  inputmode="tel" 
                  value="" 
                  required 
                />
              </div>
              <div class="quick-order-modal-id" hidden></div>
            </div>
            <!-- MODAL-QUICK-ORDER button -->
            <button class="button-main-text p-16-auto-bold disabled-button quick-order-modal-button" type="submit"
              value="Отправить" disabled>
              Відправити
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>