cart/urls.py
"""Urls list for 'userprofile' app."""

from django.urls import path

from .views import CartView

app_name = "cart"

urlpatterns = [
    path("<slug:region_slug>/cart/", CartView.as_view(), name="cart"),
]

catalogue/urls.py
"""Urls for 'catalogue' app."""

from django.urls import path

from .views import CatalogueView

app_name = "catalogue"

urlpatterns = [
    path(
        "<slug:region_slug>/<slug:category_slug>/",
        CatalogueView.as_view(),
        name="category_view",
    ),
    path(
        "<slug:region_slug>/<slug:category_slug>/<slug:subcategory_slug>/",
        CatalogueView.as_view(),
        name="subcategory_view",
    ),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("location.urls")),
    path("", include("orders.urls")),
    path("", include("feedback.urls")),
    path("", include("cart.urls")),
    path("", include("mainpage.urls")),
    path("", include("fillers.urls")),
    path("catalogue/", include("catalogue.urls")),
    path("delivery_and_payment/", include("delivery_and_payment.urls")),
    path("reviews/", include("reviews.urls")),
    path("product/", include("products.urls")),
    path("zoho-token/", include("zoho_token.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainpage/urls.py
"""Urls list for 'mainpage' app."""
from django.urls import path

from .views import MainPageView

app_name = "main_page"

urlpatterns = [
    path("", MainPageView.as_view(), name="main_page"),
    path("<slug:region_slug>/", MainPageView.as_view(), name="mainpage-view"),
]

products/urls.py
"""Urls for 'products' app."""

from django.urls import path

from .views import ProductSearchView, ProductView

app_name = "products"

urlpatterns = [
    path(
        "<slug:region_slug>/",
        ProductSearchView.as_view(),
    ),
    path(
        "<slug:region_slug>/<slug:subcategory_slug>/<slug:product_slug>/",
        ProductView.as_view(),
        name="product",
    ),
]

products/models.py
"""Models for 'product' app."""

from typing import List

from asgiref.sync import sync_to_async
from django.db import models


class ZohoModuleRecord(models.Model):
    """Model for storing Zoho CRM module id storage."""

    id = models.BigIntegerField(
        primary_key=True,
        verbose_name="Id записи",
    )
    module_name = models.CharField(
        max_length=100,
        verbose_name="Наименование модуля",
    )
    record_name = models.CharField(
        max_length=100,
        verbose_name="Наименование записи",
    )
    accessed_at = models.DateField(
        auto_now=True,
        verbose_name="Последняя дата доступа",
    )

    def __str__(self) -> str:
        """Represent class instance."""
        return f"{self.module_name} {self.record_name}"


class ZohoImage(models.Model):
    """Model for storing Zoho CRM images."""

    id = models.BigIntegerField(
        primary_key=True,
        verbose_name="Id картинки",
    )
    zoho_record = models.ForeignKey(
        ZohoModuleRecord,
        on_delete=models.CASCADE,
        verbose_name="Зохо запись",
    )
    image = models.ImageField(verbose_name="Адресс картинки")

    @classmethod
    @sync_to_async
    def avalues_list(cls, *args, **kwargs) -> List:
        """
        Async implementation of "filter" method.

        Is async because of this one exception:
        django.core.exceptions.SynchronousOnlyOperation:
        You cannot call this from an async context - use a thread or sync_to_async.
        """
        return list(cls.objects.filter(*args, **kwargs))

    def __str__(self) -> str:
        """Represent class instance."""
        return f"{self.image}"

products/views.py
"""Function and class views list for 'products' app."""
import json
from typing import Any, Set

from django.http import (
    HttpRequest,
    HttpResponseNotFound,
    HttpResponseServerError,
    JsonResponse,
)
from django.views import View

from async_views.generic.base import AsyncTemplateView
from cart.app_services.session_data import session_data
from catalogue.app_services.utils import bread_crumbs
from products.app_services.data_getters import crm_data
from products.app_services.product_handlers import product_detail_handlers
from products.exceptions import BouquetSizeNotFoundError, ProductNotFoundError
from services.data_getters import crm_data as service_crm_data
from services.mixins import ApplicationMixin
from services.utils import utilities
from userprofile.app_services.userprofile_handlers import user_handlers


class ProductView(ApplicationMixin, AsyncTemplateView):
    """Class view for product detail information."""

    template_name = "products/product.html"

    async def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        """
        Get the context data for the view.

        Args:
            **kwargs (Any): Additional keyword arguments.

        Returns:
            dict: A dictionary containing the context data.
        """
        context = await self.get_common_context(**await super().get_context_data(**kwargs))
        if isinstance(context, HttpResponseServerError):
            return context
        region_slug, category_slug, subcategory_slug, product_slug = self._get_slugs(
            await service_crm_data.get_subcategories_list(), context
        )
        product_dict = await product_detail_handlers.get_product_details_for_product_view(
            region_slug, subcategory_slug, product_slug, context["selected_currency"]
        )
        self._handle_product_not_found(product_dict)
        cart: dict = await session_data.get_or_create_cart(self.request.session)
        cart_ids_set = {product["id"] for product in cart["products"]}
        region_products = await service_crm_data.get_region_products(
            context["region"]["slug"],
            currency=context["selected_currency"],
            cart_ids_set=cart_ids_set,
        )
        similar_products = await product_detail_handlers.get_first_nine_similar_products(
            region_slug,
            subcategory_slug,
            product_dict.get("id"),
            product_dict.get("bouquet_colors"),
            product_dict.get("bouquet_flowers"),
            product_dict.get("is_bouquet"),
            context["selected_currency"],
            region_products,
        )
        context["category_crumb"] = await bread_crumbs.get_category_crumb(category_slug)
        if self.is_subcat_exists:
            context["subcategory_crumb"] = await bread_crumbs.get_subcategory_crumb(
                subcategory_slug
            )
        context.update(
            self._build_context_data(
                product_dict, similar_products, category_slug, subcategory_slug, product_slug
            )
        )
        await self._refresh_customer_viewed_products(product_dict)
        return context

    async def get(self, request: HttpRequest, *args, **kwargs):
        """
        Handle the HTTP GET request for the product view.

        Args:
            request (HttpRequest): The HTTP request object.
            *args: Additional positional arguments.
            **kwargs: Additional keyword arguments.

        Returns:
            HttpResponse: The HTTP response for the request.
        """
        self.is_subcat_exists = await self._check_subcategory_existence(
            await service_crm_data.get_subcategories_list()
        )
        if self.is_subcat_exists:
            try:
                try:
                    context = await self.get_context_data(**kwargs)
                    if isinstance(context, HttpResponseServerError):
                        return context
                except BouquetSizeNotFoundError:
                    return HttpResponseNotFound()
            except ProductNotFoundError:
                return HttpResponseNotFound()

            cart: dict = await session_data.get_or_create_cart(self.request.session)
            if (product := context["product"])["is_bouquet"]:
                try:
                    self._handle_bouquet_size(request, product, context)
                except BouquetSizeNotFoundError:
                    return HttpResponseNotFound()
                for cart_product in cart["products"]:
                    if (
                        cart_product["id"] == context["product"]["id"]
                        and cart_product["size"] == context["selected_bouquet_size"]["value"]
                    ):
                        context["product"]["is_in_cart"] = True
                        context["product"]["cart_amount"] = cart_product["amount"]
                        break
                else:
                    context["product"]["is_in_cart"] = False
            else:
                for cart_product in cart["products"]:
                    if context["product"]["id"] == cart_product["id"]:
                        context["product"]["is_in_cart"] = True
                        context["product"]["cart_amount"] = cart_product["amount"]
                        break
                else:
                    context["product"]["is_in_cart"] = False
            return self.render_to_response(context)
        return HttpResponseNotFound()

    def _get_slugs(self, subcategories_list: list[dict[str, str]], context: dict[str, str]):
        """
        Extract and return region, category, subcategory, and product slugs.

        Args:
            subcategories_list (list[dict[str, str]]): List of subcategories.
            context (dict[str, str]): The context dictionary.

        Returns:
            Tuple: A tuple containing region_slug, category_slug,
            subcategory_slug, and product_slug.
        """
        region_slug = context["region"]["slug"]
        category_slug = next(
            (
                subcat["category_slug"]
                for subcat in subcategories_list
                if subcat["slug"] == self.kwargs["subcategory_slug"]
            ),
            None,
        )
        subcategory_slug = self.kwargs.get("subcategory_slug")
        product_slug = self.kwargs.get("product_slug")
        return region_slug, category_slug, subcategory_slug, product_slug

    def _handle_product_not_found(self, product_dict):
        """
        Raise a ProductNotFoundError if the product is not found.

        Args:
            product_dict: The product dictionary to check.
        """
        if not product_dict:
            raise ProductNotFoundError()

    def _build_context_data(
        self, product_dict, similar_products, category_slug, subcategory_slug, product_slug
    ):
        """
        Build the context data dictionary.

        Args:
            product_dict: The product dictionary.
            similar_products: List of similar products.
            category_slug: The category slug.
            subcategory_slug: The subcategory slug.
            product_slug: The product slug.

        Returns:
            dict: The context data dictionary.
        """
        context_data = {
            "product": product_dict,
            "similar_products": similar_products,
            "title": product_dict.get("Name"),
            "subcategory_slug": subcategory_slug,
            "category_slug": category_slug,
            "product_slug": product_slug,
        }
        return context_data

    async def _refresh_customer_viewed_products(self, product_dict):
        """
        Refresh the customer viewed products in the session.

        Args:
            product_dict: The product dictionary to use for refreshing.
        """
        """
        Check if the subcategory exists in the list.

        Args:
            subcategories_list (list[dict[str, str]]): List of subcategories.

        Returns:
            bool: True if the subcategory exists, otherwise False.
        """
        if product_id := product_dict.get("id"):
            await user_handlers.refresh_customer_viewed_products(
                self.request.session, product_id
            )

    async def _check_subcategory_existence(self, subcategories_list: list[dict[str, str]]):
        """
        Check if the subcategory exists in the list.

        Args:
            subcategories_list (list[dict[str, str]]): List of subcategories.

        Returns:
            bool: True if the subcategory exists, otherwise False.
        """
        subcategory_slug = self.kwargs["subcategory_slug"]
        return subcategory_slug in (subcat["slug"] for subcat in subcategories_list)

    def _handle_bouquet_size(self, request, product, context):
        """
        Handle the selected bouquet size.

        Args:
            request (HttpRequest): The HTTP request object.
            product: The product dictionary.
            context: The context dictionary.

        Returns:
            HttpResponse: The HTTP response for handling the bouquet size.
        """
        if not request.GET.get("size"):
            context["selected_bouquet_size"] = product["bouquet_sizes"][0]

        else:
            for size in product["bouquet_sizes"]:
                if request.GET.get("size") == str(size["value"]):
                    context["selected_bouquet_size"] = size
                    break
            else:
                raise BouquetSizeNotFoundError()


class ProductSearchView(View, ApplicationMixin):
    """
    Class view for searching products.

    Inherits from View.

    Usage:
    To use this view, define the URL pattern in your urls.py and map it to this
    view class. When a GET request is made to the defined URL, this view will search
    for products based on the 'search' query parameter in the request.GET dictionary.

products/templates/products/product.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{ product.Name }}</title>

  <!-- FAVICON -->

  <link rel="shortcut icon" href="{% static 'mainpage/favicon.svg' %}" type="image/x-icon" />

  <!-- FOR-PHONE-INPUT -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

  <!-- BOOTSTRAP -->

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

  <!-- SITE-STYLE -->

  <link rel="stylesheet" href="{% static 'styles/common.css' %}">
  <link rel="stylesheet" href="{% static 'products/product.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/header.css' %}">
  <link rel="stylesheet" href="{% static 'styles/footer.css' %}">
  <link rel="stylesheet" href="{% static 'styles/sideButtons.css' %}">
  <link rel="stylesheet" href="{% static 'styles/counter.css' %}">
  <link rel="stylesheet" href="{% static 'styles/quickOrderModal.css' %}">
  <link rel="stylesheet" href="{% static 'styles/callBackModal.css' %}">
  <link rel="stylesheet" href="{% static 'styles/cardXlForSlider.css' %}">
  <link rel="stylesheet" href="{% static 'styles/breadcrumbs.css' %}">

</head>

<body>
  <!-- HEADER -->
  {% include 'core_components/header.html' %}

  <main>
    <!-- BREADCRUMBS -->
    <div class="container product-container">
      <div class="breadcrumbs product-breadcrumbs">
        <!-- ARROW-LEFT -->
        <a href="{% url 'main_page:mainpage-view' region.slug %}?currency={{ selected_currency.Name }}" class="icon darck-gray"></a>
        <!-- LINK`S LIST -->
        <ul>
          <li>
            <a 
              href="{% url 'catalogue:category_view' region.slug category_slug %}?currency={{ selected_currency.Name }}" 
              class="p-14-auto-regular breadcrumbs-link"
            >
              {{ category_crumb.title }}
            </a>
          </li>

          {% if subcategory_crumb %}
            <li>
              <a 
                href="{% url 'catalogue:subcategory_view' region.slug category_slug subcategory_slug %}?currency={{ selected_currency.Name }}" 
                class="p-14-auto-regular breadcrumbs-link"
              >
                {{ subcategory_crumb.title }}
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>

    <div class="product-top-data product-top-data-mobile">
      <div class="product-title-container">
        <h4 class="h1-42-auto-bold">{{ product.Name }}</h4>
        <p class="p-16-auto-regular">Артикул: {{ product.sku }}</p>
      </div>
      <p class="button-main-text p-14-auto-medium product-title-button">В Наявності</p>
    </div>

    <div class="container product-content m-b-60">
      <!-- /* <-- PRODUCT IMAGE SLIDER -->
      <div class="product-slider-container">
        <div class="product-viewer">
          <div class="product-slides">
            {% for image in product.images %}
              <div class="product-slide">
                <div class="product-img"
                  style="background-image: url({{image.url}});">
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="product-slider-buttons"></div>
      </div>

      <!-- PRODUCT CONTENT -->
      <div 
      class="product-data-container product-card" 
      data-product-id="{{ product.id }}" 
      data-region="{{ region.slug }}" 
      data-is-bouquet="{{ product.is_bouquet }}"
      data-selected-size="{{ selected_bouquet_size.value }}">
        <div class="product-top-data-container">
          <div class="product-top-data">
            <div class="product-title-container">
              <h4 class="h1-42-auto-bold">{{ product.Name }}</h4>
              <p class="p-16-auto-regular">Артикул: {{ product.sku }}</p>
            </div>
            <p class="button-main-text p-14-auto-medium product-title-button">В Наявності</p>
          </div>

          <!-- This block will be hidden If product category is not a “bouquet” -->
          {% if product.is_bouquet %} 
            <div class="product-sizes-data">
              <p class="p-16-auto-regular product-size-title">Розмір:</p>
              <div class="">
                <ul class="product-sizes">
                  {% for size in product.bouquet_sizes %}
                    <li>
                      <input 
                        class="form-check-input product-size" 
                        type="radio"
                        name="categoryName"
                        id="product-size-{{ size.value }}"
                        data-size="{{ size.value }}"
                        hidden 
                      />
                      <label for="product-size-{{ size.value }}" class="product-size-label">
                        <a href="?size={{ size.value }}&currency={{ selected_currency.Name }}" class="p-16-auto-medium">
                          {{ size.value }}см
                        </a>
                      </label>
                    </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          {% endif %}

          <div class="product-instruction-data">
            <span class="icon product-instruction-icon"></span>
            <p class="p-14-auto-regular">Ціна під кожне замовлення індивідуальна і поточнюється у менеджера</p>
          </div>

          <div class="product-price-data">
            <div class="product-price-group">
              <p class="p-16-auto-regular">Ціна:</p>
              <div class="product-price-value">
                <p class="h2-24-auto-medium red">
                  {% if product.discount %}
                    {% if product.is_bouquet %}
                      {{ selected_bouquet_size.new_price }}
                    {% else %}
                      {{ product.new_price }}
                    {% endif %}
                  {% else %}
                    {% if product.is_bouquet %}
                      {{ selected_bouquet_size.price }}
                    {% else %}
                      {{ product.unit_price }}
                    {% endif %}
                  {% endif %}
                  {{ selected_currency.symbol }}
                </p>
                {% if product.discount %}
                  <div class="old-price">
                      <p class="p-16-auto-medium grey">
                        {% if product.is_bouquet %}
                          {{ selected_bouquet_size.price }}
                        {% else %}
                          {{ product.unit_price }}
                        {% endif %}
                        {{ selected_currency.symbol }}
                      </p>
                  </div>
                {% endif %}
              </div>
            </div>
          </div>

            <button
              type="button"
              class="button-main-text-icon p-16-auto-bold product-cart-button add-to-cart"
              data-is-added="{{ product.is_in_cart }}"
            >
              <span class="icon"></span>
              До кошика
            </button>
            <!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->
            <div
              class="product-cart-button-added"
              hidden
            >
              <button class="delete-button icon remove-from-cart"></button>
              {% include 'core_components/counter.html' %}
            </div>
          <!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->
        </div>

        <a
          href="#"
          class="p-16-auto-regular red quick-order-link product-quick-order"
          data-bs-toggle="modal"
          data-bs-target="#quickOrderModal"
          data-product-article="{{ product.sku }}"
          data-product-image="{{ product.images.0.url }}"
          data-product-title="{{ product.Name }}"
          data-product-discount-price="{{ product.new_price }}"
          data-product-price="
            {{ product.unit_price }}
          "
          data-product-id="{{ product.id }}"
          data-product-currency="{{ selected_currency.symbol }}"
        >
          Швидке замовлення
        </a>

        <div class="product-bottom-data-container">
          <div class="accordion-category product-description-container" id="accordionDescription">
            <div class="accordion-item product-description">
              <h2 class="accordion-header" id="headingOne">
                <button
                  type="button"
                  class="accordion-button collapsed p-16-auto-medium"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapseDescription"
                  aria-expanded="false"
                  aria-controls="collapseDescription"
                >
                  Опис
                  <span class="accordion-button-arrow"></span>
                </button>
              </h2>
              <div
                class="accordion-collapse collapse"
                id="collapseDescription"
                aria-labelledby="headingCategory"
                data-bs-parent="#accordionDescription"
              >
                <div class="accordion-body category-list">
                  <p class="p-14-auto-regular">{{ product.desc }}</p>
                </div>
              </div>
            </div>
          </div>

          <div class="accordion-category product-description-container" id="accordionCharacteristics">
            <div class="accordion-item product-description">
              <h2 class="accordion-header" id="headingOne">
                <button
                  type="button"
                  class="accordion-button collapsed p-16-auto-medium"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapseCharacteristics"
                  aria-expanded="false"
                  aria-controls="collapseCharacteristics"
                >
                  Характеристики
                  <span class="accordion-button-arrow"></span>
                </button>
              </h2>
              <div
                class="accordion-collapse collapse"
                id="collapseCharacteristics"
                aria-labelledby="headingCategory"
                data-bs-parent="#accordionCharacteristics"
              >
                <div class="accordion-body category-list">
                  <p class="p-14-auto-regular">{{ product.specs }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- SIMILAR PRODUCTS SECTION -->
    <section class="slider-for-cards m-b-60">
      <div class="slider-for-cards-container">
        <div class="title-box m-b-70">
          <h4 class="h1-42-auto-bold">Схожі товари</h4>
        </div>
        <div class="slider-product-container">
          <div class="slide_viewer">
            <div class="slide_group our-bestsellers-slider">
              <div class="slide-card-container">
                {% for product in similar_products %}
                  {% include 'core_components/cardXlForSlider.html' %}

                  {% if forloop.counter|divisibleby:3 %}
                    </div>
                    <div class="slide-card-container">
                  {% endif %}
                {% endfor %}
              </div>

            </div>
          </div>
          <a href="#" class="slide_buttons"></a>
        </div>
      </div>
    </section>
    <!-- MODALS -->

    <!-- MODAL-CALL-BACK -->
    {% include 'core_components/callBackModal.html' %}
    <!-- MODAL-USER-LOCATION -->
    {% include 'core_components/locationModal.html' %}

    <!-- MODAL-QUICK-ORDER -->
    {% include 'core_components/quickOrderModal.html' %}

    <!-- SOCIALS BUTTONS -->
    {% include 'core_components/buttons.html' %}
  </main>

  <!-- FOOTER -->
  {% include 'core_components/footer.html' %}

  <!-- SCRIPT`S -->

  <!-- BOOTSTRAP-BUNDLE-MIN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- AXIOS -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

  <!-- TEL FLAGS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/intlTelInput.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/css/intlTelInput.css" rel="stylesheet" />

  <!-- Places в Maps JavaScript API -->
  <script src="{% static 'scripts/locationModal.js' %}"></script>

  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5i5JJfxtMemi02YamAeiMa1FqYbOqCQA&libraries=places&language=en&callback=initAutocomplete" async defer>
  </script>

  <!-- OWN JS CODE -->
  <script src="{% static 'scripts/header.js' %}"></script>
  <script src="{% static 'scripts/common.js' %}"></script>
  <script src="{% static 'products/product.js' %}"></script>
  <script src="{% static 'scripts/sliderForCards.js' %}"></script>
  <script src="{% static 'scripts/sideButtons.js' %}"></script>
  <script src="{% static 'scripts/quickOrderModal.js' %}"></script>
  <script src="{% static 'scripts/callBackModal.js' %}"></script>
  <script src="{% static 'scripts/addToCart.js' %}"></script>
  <script src="{% static 'scripts/removeFromCart.js' %}"></script>
  <script src="{% static 'scripts/counter.js' %}"></script>
</body>

</html>